version: '3.8'

services:

#mysql image
  mysql:
    image: mysql:5.7
    container_name: lara_mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      #- ./docker/mysql/based.sql:/docker-entrypoint-initdb.d/based.sql
    ports:
      - 4306:4306
    environment:
      #MYSQL_DATABASE: apilaravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - tempest

#phpmyadmin image
  phpmyadmin:
    image: phpmyadmin
    container_name: lara_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
        - tempest

#php image
  php_fpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/
    container_name: lara_php
    # volumes:
      # - lara-volume:/var/www
    depends_on:
      - mysql
    networks:
      - tempest

#ngnix server image
  nginx_url:
    image: nginx:latest
    container_name: lara_nginx
    restart: unless-stopped
    networks:
      - tempest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - lara-volume:/var/www/
    depends_on:
      - php_fpm
      - mysql
    ports:
      - "8000:80"

networks:
  tempest:
    driver: bridge